---
title: "R Notebook"
output: html_notebook
---

## Questions
What are the different frequencies between blogs, news and twitter?

This is a predictive question?  Predict a word using the preceeding 1,2,3 words

  
## Stage: Understanding the problem  

#### What do the data look like?  

text file

#### Where do the data come from?  

swiftkey

#### Can you think of any other data sources that might help you in this project?  

#### other sources of text data
-government sources
-books
-corpus sets in R

#### What are the common steps in natural language processing?  

* Gather data  
* Clean Data/Tokenization  
* Tokenization: Large chunk of text in small  
* Normalization: converting all text to the same case (upper or lower), removing punctuation, expanding contractions, converting numbers to their word equivalents, and so on.  
* Stemming Stemming is the process of eliminating affixes (suffixed, prefixes, infixes, circumfixes) from a word in order to obtain a word stem.  
* Lemmatization: Lemmatization is related to stemming, differing in that lemmatization is able to capture canonical forms based on a word's.  
* Corpus:  
* Stop Words  
* Parts-of-speech (POS) Tagging  
* Bag of Words: Bag of words is a particular representation model used to simplify the contents of a selection of text.  
* Regular Expressions: Regular expressions, often abbreviated regexp or regexp, are a tried and true method of concisely describing patterns of text.  
* Similarity Measures  



#### What are some common issues in the analysis of text data?  
* Too much data to process  
* Not enough data to perfectly model in language  

#### What is the relationship between NLP and the concepts you have learned in the Specialization?  
* Cleaning data  
* Exploratory Analysis  
* Statistical Inference  
* R programming  


## Stage: Exploratory Questions
#### Some words are more frequent than others - what are the distributions of word frequencies?  
* Use word cloud, dfm measurement

#### What are the frequencies of 2-grams and 3-grams in the dataset?  
* Use word cloud, dfm measurement  

#### How many unique words do you need in a frequency sorted dictionary to cover 50% of all word instances in the language? 90%?  
  
#### How do you evaluate how many of the words come from foreign languages?
  
#### Can you think of a way to increase the coverage -- identifying words that may not be in the corpora or using a smaller number of words in the dictionary to cover the same number of phrases?
wordstem, lemmazation

## Stage: Modelling

#### Tasks to accomplish

Build basic n-gram model - using the exploratory analysis you performed, build a basic n-gram model for predicting the next word based on the previous 1, 2, or 3 words.
Build a model to handle unseen n-grams - in some cases people will want to type a combination of words that does not appear in the corpora. Build a model to handle cases where a particular n-gram isn't observed.


#### How can you efficiently store an n-gram model (think Markov Chains)?
How can you use the knowledge about word frequencies to make your model smaller and more efficient?
How many parameters do you need (i.e. how big is n in your n-gram model)?
Can you think of simple ways to "smooth" the probabilities (think about giving all n-grams a non-zero probability even if they aren't observed in the data) ?
How do you evaluate whether your model is any good?
How can you use backoff models to estimate the probability of unobserved n-grams?
Hints, tips, and tricks

As you develop your prediction model, two key aspects that you will have to keep in mind are the size and runtime of the algorithm. These are defined as:

Size: the amount of memory (physical RAM) required to run the model in R
Runtime: The amount of time the algorithm takes to make a prediction given the acceptable input
Your goal for this prediction model is to minimize both the size and runtime of the model in order to provide a reasonable experience to the user.

Keep in mind that currently available predictive text models can run on mobile phones, which typically have limited memory and processing power compared to desktop computers. Therefore, you should consider very carefully (1) how much memory is being used by the objects in your workspace; and (2) how much time it is taking to run your model. Ultimately, your model will need to run in a Shiny app that runs on the shinyapps.io server.

Tips, tricks, and hints

Here are a few tools that may be of use to you as you work on their algorithm:

object.size(): this function reports the number of bytes that an R object occupies in memory
Rprof(): this function runs the profiler in R that can be used to determine where bottlenecks in your function may exist. The profr package (available on CRAN) provides some additional tools for visualizing and summarizing profiling data.
gc(): this function runs the garbage collector to retrieve unused RAM for R. In the process it tells you how much memory is currently being used by R.
There will likely be a tradeoff that you have to make in between size and runtime. For example, an algorithm that requires a lot of memory, may run faster, while a slower algorithm may require less memory. You will have to find the right balance between the two in order to provide a good experience to the user.


The goal of this exercise is to build and evaluate your first predictive model. You will use the n-gram and backoff models you built in previous tasks to build and evaluate your predictive model. The goal is to make the model efficient and accurate.

Tasks to accomplish

Build a predictive model based on the previous data modeling steps - you may combine the models in any way you think is appropriate.
Evaluate the model for efficiency and accuracy - use timing software to evaluate the computational complexity of your model. Evaluate the model accuracy using different metrics like perplexity, accuracy at the first word, second word, and third word.
Questions to consider

How does the model perform for different choices of the parameters and size of the model?
How much does the model slow down for the performance you gain?
Does perplexity correlate with the other measures of accuracy?
Can you reduce the size of the model (number of parameters) without reducing performance?